version: "3.9"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/html

  node:
    image: node
    container_name: node
    ports:
      - 9001:9001
    restart: always  
    volumes:
      - ./backend:/application
      - ./docker-config/node/start_application.sh:/node/start_application.sh
    entrypoint: /node/start_application.sh

  mysql:
    image: mysql:5.7
    container_name: mysql-mycrud
    ports:  
      - 3306:3306
    environment:
      - MYSQL_DATABASE=my_crud
      - MYSQL_ROOT_PASSWORD=mypass
    volumes:
      - ./data:/var/lib/mysql
      - ./docker-config/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - ./docker-config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
     
    command: --init-file /docker-entrypoint-initdb.d/init.sql